image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - mkdir public
  - mv {css,js,lib,plugin}/ *html GU-Logo-schwarz.png public/

  artifacts:
    paths:
    - public
  only:
    - master
