image: "node:latest"

stages:
- build
- pages

build:
  stage: build
  script:
  - npm install
  - mkdir public
  - mv {css,js,lib,plugin}/ quandt_brussels.html public/
  artifacts:
    name: public
    expire_in: 31d
    paths:
    - public/

pages:
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - public


