image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - mkdir public
  - mv {css,js,lib,plugin}/ quandt_brussels.html public/

  artifacts:
    paths:
    - public
  only:
    - master


