image: "node:latest"

stages:
- build
- pages

build:
  stage: build
  script:
  - npm install
  - npm install --global grunt-cli
  - grunt
  - mkdir public
  - mv {ressources,css,js,lib,plugin}/ index.html quandt_brussels.html public/
  artifacts:
    name: public
    expire_in: 31d
    paths:
    - public/

# pages:
#   stage: pages
#   dependencies:
#     - build
#   artifacts:
#     paths:
#       - public/
#   only:
#     - master